dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 16
  dataset_path: ImageNet22k
  centering: sinkhorn_knopp
  OFFICIAL_EPOCH_LENGTH: 4
student:
  arch: vit_base
  num_register_tokens: 4
  patch_size: 14
  drop_path_rate: 0.0
  ffn_layer: mlp
  pretrained_weights: /home/nikola.jovisic.ivi/nj/dinov2/dinov2_vitb14_reg4_pretrain.pth
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500000
  weight_decay_end: 0.2
  base_lr: 1.875e-05  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  global_crops_size: 518
  local_crops_size: 98
